models:
  - type: main
    engine: nim
    model: meta/llama-3.1-70b-instruct
    parameters:
      api_key:
      base_url: https://integrate.api.nvidia.com/v1

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check output
